name = "developers-pvtool-docs"
type = "webpack"
account_id = "de3d96f009b57653880e5891598b8fd6" # developers-pvtool-docs.leafcolor.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "de3d96f009b57653880e5891598b8fd6" # developers-pvtool-docs.leafcolor.workers.dev
zone_id = "7c51ebd9c209329d4cf2d4bb3eb5c4b6"
route = "https://developers.pvtool.com/*"

[site]
bucket = "./public"
entry-point = "workers-site"
